### ISSUE TITLE
Rate component erases all data

### ISSUE THREAD

**Issue by ahmedwab** [ahmedwab/Twizzle#33]
Fix rate component to only remove additional stars/rating when rating from a higher to lower score
Example:
- Five star rating to three star rating should only deselect 2 stars

You can check out the functionality here:
https://components.twizzlelibrary.com/?path=/story/components-input-rate--rate-component

**Comment by JStruk** [comment]
Hey @ahmedwab going to take a look at this!

**Comment by JStruk** [comment]
hey @ahmedwab going to take a look at this!
